# Generated by Django 4.1.5 on 2023-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0002_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='home', max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
