# Generated by Django 4.1.5 on 2023-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0003_menu_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='level',
            new_name='mptt_level',
        ),
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='порядок сортировки'),
        ),
    ]
